### ISSUE TITLE
Your wiki page on updating PHP notes adding PPA - don't do that!

### ISSUE THREAD

**Issue by JedMeister** [alfreddagenais/turnkeylinux-wordpress-helper#1]
Hi there,

Glad to see that TurnKey is of use to you and great work on writing up your docs. Although having said that, it's worth being aware that the [docs section of our website](https://www.turnkeylinux.org/docs) is a wiki and any registered user can create a new page and/or update pages there. Regardless, good work on writing it up.

A TurnKey user lead me to your [wiki page on changing PHP version](https://github.com/alfreddagenais/turnkeylinux-wordpress-helper/wiki/Upgrade-PHP-Wordpress-Turnkey-Linux-From-7.3-to-7.4-Debian) and at step 6 it notes adding the Ubuntu PPA.

Please note that is not advisable and is considered a [FrankenDebian](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian)! Whilst they are built from (mostly) the same source, Ubuntu and Debian(/TurnKey) are NOT binary compatible. Whilst it may work many times, it's almost guaranteed to bite you at some point...

Could you please remove step 6. Thank you. :smile:

**Comment by alfreddagenais** [comment]
Thank you @JedMeister I just saw [the post](https://www.turnkeylinux.org/forum/support/mon-20220124-0551/need-update-tkl-wordpress-php-74) on your forum about this issue.

I wrote this documentation awhile a go to help others, because I did not see any help about that.

**Comment by JedMeister** [comment]
Thanks! :smile:
